spring:
  main:
    banner-mode: "off"
  liquibase.change-log: classpath:db/db.changelog-master.xml
  datasource:
    url: jdbc:sqlite:JavaCore/src/main/resources/Liquibase-test.db
    driver-class-name: org.sqlite.JDBC

