apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: umb
spec:
  replicas: 1
  selector: # Какими подами управляет deployment
    matchLabels:
      app: umb
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels: # Метки подов, которые создает Deployment
        app: umb
        version: v1
    spec:
      containers: # Контейнеры в поде
        - name: umb
          image: changeit # меняется в Publish.groovy
          imagePullPolicy: Always # Стратегия загрузки образа из registry
          readinessProbe: # Проверка готовности контейнера
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe: # Проверка работоспособности контейнера
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 3
          resources: # Ресурсы контейнера
            limits:
              cpu: 1000m
              memory: 1200Mi
            requests:
              cpu: 1000m
              memory: 1200Mi
          #          envFrom: # Переменные окружения в контейнере из configMap, невалидные имена отбрасываются
          #            - configMapRef:
          #                name: spasibo-config
          env: # Переменные окружения в контейнере
            - name: PROJECT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts: # Монтирование томов в контейнер
            #            - name: application-config
            #              mountPath: "/deployments/config"
            #              readOnly: true
            - mountPath: /opt/synapse/logs
              name: synapselogs
            - mountPath: /fluent-bit/etc/
              name: fluent-bit
              readOnly: true

        - env: # образ компонента, осуществляющего отправку прикладных логов в Kafka
            - name: fluent-bit
          image: >-
            registry.ca.sbrf.ru/ci00734898/ci00685811_synapse/fluent-bit:1.2.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 50m
              memory: 60Mi
            requests:
              cpu: 5m
              memory: 30Mi
          name: fluent-bit
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/synapse/logs
              name: synapselogs
            - mountPath: /fluent-bit/etc/
              name: fluent-bit
              readOnly: true
      terminationGracePeriodSeconds: 80 # Время, в течение которого OpenShift ожидает нормального завершения контейнера,
      # после чего процессы в поде убиваются kill сигналом. По умолчанию 30
      volumes: # Определение томов пода
        #        - name: application-config
        #          configMap: # Файлы в томе взять из configMap
        #            name: spasibo-config
        #            items: # Из configMap взять определенное значение (файлы) и добавить в директорию.
        #                   # Без items при монтировании перезаписывает все в диретории
        #              - key: application.properties
        #                path: application.properties
        - emptyDir: {}
          name: synapselogs
        - configMap:
            defaultMode: 420
            name: fluent-bit
          name: fluent-bit