---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: ${namespace.name}
secrets:
  - name: prometheus-token

---

apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  namespace: ${namespace.name}
roleRef:
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: ${namespace.name}

---

apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: prometheus
  name: prometheus-token
  namespace: ${namespace.name}
type: kubernetes.io/service-account-token